### ISSUE TITLE
半精度overflow

### ISSUE THREAD

**Issue by JaheimLee** [JunnYu/GAU-alpha-pytorch#1]
https://github.com/JunnYu/GAU-alpha-pytorch/blob/b7ba52e022ea8da19fbb0698c2063ca34c3679b9/src/gau_alpha/layer.py#L140
半精度训练的时候，这里会报overflow问题。我又去翻了你roformer的mask代码，那里attention mask的是-10000

**Comment by JunnYu** [comment]
好的谢谢指出，现在已经修改`INF=1e4`
